# Generated by Django 4.2 on 2025-11-20 17:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='recipe_files/')),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('cooking_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('difficulty', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recipetable',
            index=models.Index(fields=['recipe_name'], name='core_recipe_recipe__3d4d73_idx'),
        ),
        migrations.AddIndex(
            model_name='recipetable',
            index=models.Index(fields=['-views'], name='core_recipe_views_a1faa4_idx'),
        ),
    ]
